### ISSUE TITLE
Resolve EOL mystery 🧙‍♂️

### ISSUE THREAD

**Issue by iammatis** [iammatis/iKalendar#27]
Why is `.replace(/\r\n\s/g, '')` not enough on iCal string ? Addition of `.replace(/\r/g, '')` seems to do the magic.

**Comment by PhilippJust** [comment]
`\r\n\s` Would be a carriage return followed by a line break followed by another "whitespace" character, right? 
In most cases I'd expect to only see `\r\n` without another whitespace character.

Have you tried `replace(/\r?\n/g, '')` This should cover all linebreaks, even those that don't have the carriage return.

**Comment by iammatis** [comment]
Yes you are right, I eventually figured out the `/\r?\n/g` regex, I just still have some mess left (the leftover `\s` and `|\r` parts of the regex), so I'll try to fix that in next release.
